// source: cs3/permissions/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var cs3_identity_group_v1beta1_resources_pb = require('../../../cs3/identity/group/v1beta1/resources_pb.js');
goog.object.extend(proto, cs3_identity_group_v1beta1_resources_pb);
var cs3_identity_user_v1beta1_resources_pb = require('../../../cs3/identity/user/v1beta1/resources_pb.js');
goog.object.extend(proto, cs3_identity_user_v1beta1_resources_pb);
goog.exportSymbol('proto.cs3.permissions.v1beta1.SubjectReference', null, global);
goog.exportSymbol('proto.cs3.permissions.v1beta1.SubjectReference.SpecCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.permissions.v1beta1.SubjectReference = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.cs3.permissions.v1beta1.SubjectReference.oneofGroups_);
};
goog.inherits(proto.cs3.permissions.v1beta1.SubjectReference, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.permissions.v1beta1.SubjectReference.displayName = 'proto.cs3.permissions.v1beta1.SubjectReference';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.cs3.permissions.v1beta1.SubjectReference.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.cs3.permissions.v1beta1.SubjectReference.SpecCase = {
  SPEC_NOT_SET: 0,
  USER_ID: 1,
  GROUP_ID: 2
};

/**
 * @return {proto.cs3.permissions.v1beta1.SubjectReference.SpecCase}
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.getSpecCase = function() {
  return /** @type {proto.cs3.permissions.v1beta1.SubjectReference.SpecCase} */(jspb.Message.computeOneofCase(this, proto.cs3.permissions.v1beta1.SubjectReference.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.permissions.v1beta1.SubjectReference.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.permissions.v1beta1.SubjectReference} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.permissions.v1beta1.SubjectReference.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: (f = msg.getUserId()) && cs3_identity_user_v1beta1_resources_pb.UserId.toObject(includeInstance, f),
    groupId: (f = msg.getGroupId()) && cs3_identity_group_v1beta1_resources_pb.GroupId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.permissions.v1beta1.SubjectReference}
 */
proto.cs3.permissions.v1beta1.SubjectReference.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.permissions.v1beta1.SubjectReference;
  return proto.cs3.permissions.v1beta1.SubjectReference.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.permissions.v1beta1.SubjectReference} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.permissions.v1beta1.SubjectReference}
 */
proto.cs3.permissions.v1beta1.SubjectReference.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_identity_user_v1beta1_resources_pb.UserId;
      reader.readMessage(value,cs3_identity_user_v1beta1_resources_pb.UserId.deserializeBinaryFromReader);
      msg.setUserId(value);
      break;
    case 2:
      var value = new cs3_identity_group_v1beta1_resources_pb.GroupId;
      reader.readMessage(value,cs3_identity_group_v1beta1_resources_pb.GroupId.deserializeBinaryFromReader);
      msg.setGroupId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.permissions.v1beta1.SubjectReference.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.permissions.v1beta1.SubjectReference} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.permissions.v1beta1.SubjectReference.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_identity_user_v1beta1_resources_pb.UserId.serializeBinaryToWriter
    );
  }
  f = message.getGroupId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_identity_group_v1beta1_resources_pb.GroupId.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.identity.user.v1beta1.UserId user_id = 1;
 * @return {?proto.cs3.identity.user.v1beta1.UserId}
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.getUserId = function() {
  return /** @type{?proto.cs3.identity.user.v1beta1.UserId} */ (
    jspb.Message.getWrapperField(this, cs3_identity_user_v1beta1_resources_pb.UserId, 1));
};


/**
 * @param {?proto.cs3.identity.user.v1beta1.UserId|undefined} value
 * @return {!proto.cs3.permissions.v1beta1.SubjectReference} returns this
*/
proto.cs3.permissions.v1beta1.SubjectReference.prototype.setUserId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.cs3.permissions.v1beta1.SubjectReference.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.permissions.v1beta1.SubjectReference} returns this
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.clearUserId = function() {
  return this.setUserId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.hasUserId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.identity.group.v1beta1.GroupId group_id = 2;
 * @return {?proto.cs3.identity.group.v1beta1.GroupId}
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.getGroupId = function() {
  return /** @type{?proto.cs3.identity.group.v1beta1.GroupId} */ (
    jspb.Message.getWrapperField(this, cs3_identity_group_v1beta1_resources_pb.GroupId, 2));
};


/**
 * @param {?proto.cs3.identity.group.v1beta1.GroupId|undefined} value
 * @return {!proto.cs3.permissions.v1beta1.SubjectReference} returns this
*/
proto.cs3.permissions.v1beta1.SubjectReference.prototype.setGroupId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.cs3.permissions.v1beta1.SubjectReference.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.permissions.v1beta1.SubjectReference} returns this
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.clearGroupId = function() {
  return this.setGroupId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.permissions.v1beta1.SubjectReference.prototype.hasGroupId = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.cs3.permissions.v1beta1);
