// source: cs3/tx/v1beta1/tx_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var cs3_rpc_v1beta1_status_pb = require('../../../cs3/rpc/v1beta1/status_pb.js');
goog.object.extend(proto, cs3_rpc_v1beta1_status_pb);
var cs3_sharing_ocm_v1beta1_resources_pb = require('../../../cs3/sharing/ocm/v1beta1/resources_pb.js');
goog.object.extend(proto, cs3_sharing_ocm_v1beta1_resources_pb);
var cs3_tx_v1beta1_resources_pb = require('../../../cs3/tx/v1beta1/resources_pb.js');
goog.object.extend(proto, cs3_tx_v1beta1_resources_pb);
var cs3_types_v1beta1_types_pb = require('../../../cs3/types/v1beta1/types_pb.js');
goog.object.extend(proto, cs3_types_v1beta1_types_pb);
goog.exportSymbol('proto.cs3.tx.v1beta1.CancelTransferRequest', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.CancelTransferResponse', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.GetTransferStatusRequest', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.GetTransferStatusResponse', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.ListTransfersRequest', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.ListTransfersRequest.Filter', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.TermCase', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.Type', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.ListTransfersResponse', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.PullTransferRequest', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.PullTransferResponse', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.RetryTransferRequest', null, global);
goog.exportSymbol('proto.cs3.tx.v1beta1.RetryTransferResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.PullTransferRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.tx.v1beta1.PullTransferRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.PullTransferRequest.displayName = 'proto.cs3.tx.v1beta1.PullTransferRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.PullTransferResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.tx.v1beta1.PullTransferResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.PullTransferResponse.displayName = 'proto.cs3.tx.v1beta1.PullTransferResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.tx.v1beta1.GetTransferStatusRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.GetTransferStatusRequest.displayName = 'proto.cs3.tx.v1beta1.GetTransferStatusRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.tx.v1beta1.GetTransferStatusResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.GetTransferStatusResponse.displayName = 'proto.cs3.tx.v1beta1.GetTransferStatusResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.CancelTransferRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.tx.v1beta1.CancelTransferRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.CancelTransferRequest.displayName = 'proto.cs3.tx.v1beta1.CancelTransferRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.CancelTransferResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.tx.v1beta1.CancelTransferResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.CancelTransferResponse.displayName = 'proto.cs3.tx.v1beta1.CancelTransferResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.ListTransfersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.tx.v1beta1.ListTransfersRequest.repeatedFields_, null);
};
goog.inherits(proto.cs3.tx.v1beta1.ListTransfersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.ListTransfersRequest.displayName = 'proto.cs3.tx.v1beta1.ListTransfersRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.oneofGroups_);
};
goog.inherits(proto.cs3.tx.v1beta1.ListTransfersRequest.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.displayName = 'proto.cs3.tx.v1beta1.ListTransfersRequest.Filter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.ListTransfersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.tx.v1beta1.ListTransfersResponse.repeatedFields_, null);
};
goog.inherits(proto.cs3.tx.v1beta1.ListTransfersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.ListTransfersResponse.displayName = 'proto.cs3.tx.v1beta1.ListTransfersResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.RetryTransferRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.tx.v1beta1.RetryTransferRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.RetryTransferRequest.displayName = 'proto.cs3.tx.v1beta1.RetryTransferRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.tx.v1beta1.RetryTransferResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.tx.v1beta1.RetryTransferResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.tx.v1beta1.RetryTransferResponse.displayName = 'proto.cs3.tx.v1beta1.RetryTransferResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.PullTransferRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.PullTransferRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.PullTransferRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    srcTargetUri: jspb.Message.getFieldWithDefault(msg, 1, ""),
    destTargetUri: jspb.Message.getFieldWithDefault(msg, 2, ""),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.PullTransferRequest}
 */
proto.cs3.tx.v1beta1.PullTransferRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.PullTransferRequest;
  return proto.cs3.tx.v1beta1.PullTransferRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.PullTransferRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.PullTransferRequest}
 */
proto.cs3.tx.v1beta1.PullTransferRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSrcTargetUri(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDestTargetUri(value);
      break;
    case 3:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.PullTransferRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.PullTransferRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.PullTransferRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSrcTargetUri();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDestTargetUri();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional string src_target_uri = 1;
 * @return {string}
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.getSrcTargetUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.tx.v1beta1.PullTransferRequest} returns this
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.setSrcTargetUri = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string dest_target_uri = 2;
 * @return {string}
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.getDestTargetUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.tx.v1beta1.PullTransferRequest} returns this
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.setDestTargetUri = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 3;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 3));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.PullTransferRequest} returns this
*/
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.PullTransferRequest} returns this
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.PullTransferRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.PullTransferResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.PullTransferResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.PullTransferResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f),
    txInfo: (f = msg.getTxInfo()) && cs3_tx_v1beta1_resources_pb.TxInfo.toObject(includeInstance, f),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.PullTransferResponse}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.PullTransferResponse;
  return proto.cs3.tx.v1beta1.PullTransferResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.PullTransferResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.PullTransferResponse}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new cs3_tx_v1beta1_resources_pb.TxInfo;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxInfo.deserializeBinaryFromReader);
      msg.setTxInfo(value);
      break;
    case 3:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.PullTransferResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.PullTransferResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.PullTransferResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getTxInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_tx_v1beta1_resources_pb.TxInfo.serializeBinaryToWriter
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.rpc.v1beta1.Status status = 1;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 1));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.tx.v1beta1.PullTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.PullTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TxInfo tx_info = 2;
 * @return {?proto.cs3.tx.v1beta1.TxInfo}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.getTxInfo = function() {
  return /** @type{?proto.cs3.tx.v1beta1.TxInfo} */ (
    jspb.Message.getWrapperField(this, cs3_tx_v1beta1_resources_pb.TxInfo, 2));
};


/**
 * @param {?proto.cs3.tx.v1beta1.TxInfo|undefined} value
 * @return {!proto.cs3.tx.v1beta1.PullTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.setTxInfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.PullTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.clearTxInfo = function() {
  return this.setTxInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.hasTxInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 3;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 3));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.PullTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.PullTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.PullTransferResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.GetTransferStatusRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.GetTransferStatusRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    txId: (f = msg.getTxId()) && cs3_tx_v1beta1_resources_pb.TxId.toObject(includeInstance, f),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusRequest}
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.GetTransferStatusRequest;
  return proto.cs3.tx.v1beta1.GetTransferStatusRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.GetTransferStatusRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusRequest}
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_tx_v1beta1_resources_pb.TxId;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxId.deserializeBinaryFromReader);
      msg.setTxId(value);
      break;
    case 2:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.GetTransferStatusRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.GetTransferStatusRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_tx_v1beta1_resources_pb.TxId.serializeBinaryToWriter
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional TxId tx_id = 1;
 * @return {?proto.cs3.tx.v1beta1.TxId}
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.getTxId = function() {
  return /** @type{?proto.cs3.tx.v1beta1.TxId} */ (
    jspb.Message.getWrapperField(this, cs3_tx_v1beta1_resources_pb.TxId, 1));
};


/**
 * @param {?proto.cs3.tx.v1beta1.TxId|undefined} value
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusRequest} returns this
*/
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.setTxId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusRequest} returns this
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.clearTxId = function() {
  return this.setTxId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.hasTxId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 2;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 2));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusRequest} returns this
*/
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusRequest} returns this
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.GetTransferStatusRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.GetTransferStatusResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f),
    txInfo: (f = msg.getTxInfo()) && cs3_tx_v1beta1_resources_pb.TxInfo.toObject(includeInstance, f),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusResponse}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.GetTransferStatusResponse;
  return proto.cs3.tx.v1beta1.GetTransferStatusResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusResponse}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new cs3_tx_v1beta1_resources_pb.TxInfo;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxInfo.deserializeBinaryFromReader);
      msg.setTxInfo(value);
      break;
    case 3:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.GetTransferStatusResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getTxInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_tx_v1beta1_resources_pb.TxInfo.serializeBinaryToWriter
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.rpc.v1beta1.Status status = 1;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 1));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} returns this
*/
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} returns this
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TxInfo tx_info = 2;
 * @return {?proto.cs3.tx.v1beta1.TxInfo}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.getTxInfo = function() {
  return /** @type{?proto.cs3.tx.v1beta1.TxInfo} */ (
    jspb.Message.getWrapperField(this, cs3_tx_v1beta1_resources_pb.TxInfo, 2));
};


/**
 * @param {?proto.cs3.tx.v1beta1.TxInfo|undefined} value
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} returns this
*/
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.setTxInfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} returns this
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.clearTxInfo = function() {
  return this.setTxInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.hasTxInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 3;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 3));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} returns this
*/
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.GetTransferStatusResponse} returns this
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.GetTransferStatusResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.CancelTransferRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.CancelTransferRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    txId: (f = msg.getTxId()) && cs3_tx_v1beta1_resources_pb.TxId.toObject(includeInstance, f),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferRequest}
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.CancelTransferRequest;
  return proto.cs3.tx.v1beta1.CancelTransferRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.CancelTransferRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferRequest}
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_tx_v1beta1_resources_pb.TxId;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxId.deserializeBinaryFromReader);
      msg.setTxId(value);
      break;
    case 2:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.CancelTransferRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.CancelTransferRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_tx_v1beta1_resources_pb.TxId.serializeBinaryToWriter
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional TxId tx_id = 1;
 * @return {?proto.cs3.tx.v1beta1.TxId}
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.getTxId = function() {
  return /** @type{?proto.cs3.tx.v1beta1.TxId} */ (
    jspb.Message.getWrapperField(this, cs3_tx_v1beta1_resources_pb.TxId, 1));
};


/**
 * @param {?proto.cs3.tx.v1beta1.TxId|undefined} value
 * @return {!proto.cs3.tx.v1beta1.CancelTransferRequest} returns this
*/
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.setTxId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferRequest} returns this
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.clearTxId = function() {
  return this.setTxId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.hasTxId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 2;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 2));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.CancelTransferRequest} returns this
*/
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferRequest} returns this
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.CancelTransferRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.CancelTransferResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.CancelTransferResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f),
    txInfo: (f = msg.getTxInfo()) && cs3_tx_v1beta1_resources_pb.TxInfo.toObject(includeInstance, f),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferResponse}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.CancelTransferResponse;
  return proto.cs3.tx.v1beta1.CancelTransferResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.CancelTransferResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferResponse}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new cs3_tx_v1beta1_resources_pb.TxInfo;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxInfo.deserializeBinaryFromReader);
      msg.setTxInfo(value);
      break;
    case 3:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.CancelTransferResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.CancelTransferResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getTxInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_tx_v1beta1_resources_pb.TxInfo.serializeBinaryToWriter
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.rpc.v1beta1.Status status = 1;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 1));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.tx.v1beta1.CancelTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TxInfo tx_info = 2;
 * @return {?proto.cs3.tx.v1beta1.TxInfo}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.getTxInfo = function() {
  return /** @type{?proto.cs3.tx.v1beta1.TxInfo} */ (
    jspb.Message.getWrapperField(this, cs3_tx_v1beta1_resources_pb.TxInfo, 2));
};


/**
 * @param {?proto.cs3.tx.v1beta1.TxInfo|undefined} value
 * @return {!proto.cs3.tx.v1beta1.CancelTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.setTxInfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.clearTxInfo = function() {
  return this.setTxInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.hasTxInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 3;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 3));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.CancelTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.CancelTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.CancelTransferResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.ListTransfersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.ListTransfersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    filtersList: jspb.Message.toObjectList(msg.getFiltersList(),
    proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.ListTransfersRequest;
  return proto.cs3.tx.v1beta1.ListTransfersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.ListTransfersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new proto.cs3.tx.v1beta1.ListTransfersRequest.Filter;
      reader.readMessage(value,proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.deserializeBinaryFromReader);
      msg.addFilters(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.ListTransfersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.ListTransfersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.serializeBinaryToWriter
    );
  }
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.oneofGroups_ = [[2,3,4]];

/**
 * @enum {number}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.TermCase = {
  TERM_NOT_SET: 0,
  STATUS: 2,
  SHARE_ID: 3,
  TX_ID: 4
};

/**
 * @return {proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.TermCase}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.getTermCase = function() {
  return /** @type {proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.TermCase} */(jspb.Message.computeOneofCase(this, proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    status: jspb.Message.getFieldWithDefault(msg, 2, 0),
    shareId: (f = msg.getShareId()) && cs3_sharing_ocm_v1beta1_resources_pb.ShareId.toObject(includeInstance, f),
    txId: (f = msg.getTxId()) && cs3_tx_v1beta1_resources_pb.TxId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.ListTransfersRequest.Filter;
  return proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {!proto.cs3.tx.v1beta1.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 3:
      var value = new cs3_sharing_ocm_v1beta1_resources_pb.ShareId;
      reader.readMessage(value,cs3_sharing_ocm_v1beta1_resources_pb.ShareId.deserializeBinaryFromReader);
      msg.setShareId(value);
      break;
    case 4:
      var value = new cs3_tx_v1beta1_resources_pb.TxId;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxId.deserializeBinaryFromReader);
      msg.setTxId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {!proto.cs3.tx.v1beta1.Status} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getShareId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_sharing_ocm_v1beta1_resources_pb.ShareId.serializeBinaryToWriter
    );
  }
  f = message.getTxId();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      cs3_tx_v1beta1_resources_pb.TxId.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.Type = {
  TYPE_INVALID: 0,
  TYPE_STATUS: 1,
  TYPE_SHARE_ID: 2,
  TYPE_TX_ID: 3
};

/**
 * optional Type type = 1;
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.Type}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.getType = function() {
  return /** @type {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.Type} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Status status = 2;
 * @return {!proto.cs3.tx.v1beta1.Status}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.getStatus = function() {
  return /** @type {!proto.cs3.tx.v1beta1.Status} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.cs3.tx.v1beta1.Status} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.setStatus = function(value) {
  return jspb.Message.setOneofField(this, 2, proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.clearStatus = function() {
  return jspb.Message.setOneofField(this, 2, proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional cs3.sharing.ocm.v1beta1.ShareId share_id = 3;
 * @return {?proto.cs3.sharing.ocm.v1beta1.ShareId}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.getShareId = function() {
  return /** @type{?proto.cs3.sharing.ocm.v1beta1.ShareId} */ (
    jspb.Message.getWrapperField(this, cs3_sharing_ocm_v1beta1_resources_pb.ShareId, 3));
};


/**
 * @param {?proto.cs3.sharing.ocm.v1beta1.ShareId|undefined} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} returns this
*/
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.setShareId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.clearShareId = function() {
  return this.setShareId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.hasShareId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional TxId tx_id = 4;
 * @return {?proto.cs3.tx.v1beta1.TxId}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.getTxId = function() {
  return /** @type{?proto.cs3.tx.v1beta1.TxId} */ (
    jspb.Message.getWrapperField(this, cs3_tx_v1beta1_resources_pb.TxId, 4));
};


/**
 * @param {?proto.cs3.tx.v1beta1.TxId|undefined} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} returns this
*/
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.setTxId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.clearTxId = function() {
  return this.setTxId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.Filter.prototype.hasTxId = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest} returns this
*/
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Filter filters = 2;
 * @return {!Array<!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter>}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.getFiltersList = function() {
  return /** @type{!Array<!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cs3.tx.v1beta1.ListTransfersRequest.Filter, 2));
};


/**
 * @param {!Array<!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter>} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest} returns this
*/
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.setFiltersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest.Filter}
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.addFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.cs3.tx.v1beta1.ListTransfersRequest.Filter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersRequest} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersRequest.prototype.clearFiltersList = function() {
  return this.setFiltersList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.ListTransfersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.ListTransfersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f),
    transfersList: jspb.Message.toObjectList(msg.getTransfersList(),
    cs3_tx_v1beta1_resources_pb.TxInfo.toObject, includeInstance),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersResponse}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.ListTransfersResponse;
  return proto.cs3.tx.v1beta1.ListTransfersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.ListTransfersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersResponse}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new cs3_tx_v1beta1_resources_pb.TxInfo;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxInfo.deserializeBinaryFromReader);
      msg.addTransfers(value);
      break;
    case 3:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.ListTransfersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.ListTransfersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getTransfersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      cs3_tx_v1beta1_resources_pb.TxInfo.serializeBinaryToWriter
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.rpc.v1beta1.Status status = 1;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 1));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersResponse} returns this
*/
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersResponse} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated TxInfo transfers = 2;
 * @return {!Array<!proto.cs3.tx.v1beta1.TxInfo>}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.getTransfersList = function() {
  return /** @type{!Array<!proto.cs3.tx.v1beta1.TxInfo>} */ (
    jspb.Message.getRepeatedWrapperField(this, cs3_tx_v1beta1_resources_pb.TxInfo, 2));
};


/**
 * @param {!Array<!proto.cs3.tx.v1beta1.TxInfo>} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersResponse} returns this
*/
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.setTransfersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.cs3.tx.v1beta1.TxInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.tx.v1beta1.TxInfo}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.addTransfers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.cs3.tx.v1beta1.TxInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersResponse} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.clearTransfersList = function() {
  return this.setTransfersList([]);
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 3;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 3));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.ListTransfersResponse} returns this
*/
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.ListTransfersResponse} returns this
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.ListTransfersResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.RetryTransferRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.RetryTransferRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    txId: (f = msg.getTxId()) && cs3_tx_v1beta1_resources_pb.TxId.toObject(includeInstance, f),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferRequest}
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.RetryTransferRequest;
  return proto.cs3.tx.v1beta1.RetryTransferRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.RetryTransferRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferRequest}
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_tx_v1beta1_resources_pb.TxId;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxId.deserializeBinaryFromReader);
      msg.setTxId(value);
      break;
    case 2:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.RetryTransferRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.RetryTransferRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTxId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_tx_v1beta1_resources_pb.TxId.serializeBinaryToWriter
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional TxId tx_id = 1;
 * @return {?proto.cs3.tx.v1beta1.TxId}
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.getTxId = function() {
  return /** @type{?proto.cs3.tx.v1beta1.TxId} */ (
    jspb.Message.getWrapperField(this, cs3_tx_v1beta1_resources_pb.TxId, 1));
};


/**
 * @param {?proto.cs3.tx.v1beta1.TxId|undefined} value
 * @return {!proto.cs3.tx.v1beta1.RetryTransferRequest} returns this
*/
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.setTxId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferRequest} returns this
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.clearTxId = function() {
  return this.setTxId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.hasTxId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 2;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 2));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.RetryTransferRequest} returns this
*/
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferRequest} returns this
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.RetryTransferRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.tx.v1beta1.RetryTransferResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.tx.v1beta1.RetryTransferResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f),
    txInfo: (f = msg.getTxInfo()) && cs3_tx_v1beta1_resources_pb.TxInfo.toObject(includeInstance, f),
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferResponse}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.tx.v1beta1.RetryTransferResponse;
  return proto.cs3.tx.v1beta1.RetryTransferResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.tx.v1beta1.RetryTransferResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferResponse}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new cs3_tx_v1beta1_resources_pb.TxInfo;
      reader.readMessage(value,cs3_tx_v1beta1_resources_pb.TxInfo.deserializeBinaryFromReader);
      msg.setTxInfo(value);
      break;
    case 3:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.tx.v1beta1.RetryTransferResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.tx.v1beta1.RetryTransferResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getTxInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_tx_v1beta1_resources_pb.TxInfo.serializeBinaryToWriter
    );
  }
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.rpc.v1beta1.Status status = 1;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 1));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.tx.v1beta1.RetryTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TxInfo tx_info = 2;
 * @return {?proto.cs3.tx.v1beta1.TxInfo}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.getTxInfo = function() {
  return /** @type{?proto.cs3.tx.v1beta1.TxInfo} */ (
    jspb.Message.getWrapperField(this, cs3_tx_v1beta1_resources_pb.TxInfo, 2));
};


/**
 * @param {?proto.cs3.tx.v1beta1.TxInfo|undefined} value
 * @return {!proto.cs3.tx.v1beta1.RetryTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.setTxInfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.clearTxInfo = function() {
  return this.setTxInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.hasTxInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 3;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 3));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.tx.v1beta1.RetryTransferResponse} returns this
*/
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.tx.v1beta1.RetryTransferResponse} returns this
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.tx.v1beta1.RetryTransferResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.cs3.tx.v1beta1);
