// source: cs3/storage/provider/v1beta1/spaces_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var cs3_identity_user_v1beta1_resources_pb = require('../../../../cs3/identity/user/v1beta1/resources_pb.js');
goog.object.extend(proto, cs3_identity_user_v1beta1_resources_pb);
var cs3_rpc_v1beta1_status_pb = require('../../../../cs3/rpc/v1beta1/status_pb.js');
goog.object.extend(proto, cs3_rpc_v1beta1_status_pb);
var cs3_storage_provider_v1beta1_resources_pb = require('../../../../cs3/storage/provider/v1beta1/resources_pb.js');
goog.object.extend(proto, cs3_storage_provider_v1beta1_resources_pb);
var cs3_types_v1beta1_types_pb = require('../../../../cs3/types/v1beta1/types_pb.js');
goog.object.extend(proto, cs3_types_v1beta1_types_pb);
var google_protobuf_field_mask_pb = require('google-protobuf/google/protobuf/field_mask_pb.js');
goog.object.extend(proto, google_protobuf_field_mask_pb);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.TermCase', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.Type', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest', null, global);
goog.exportSymbol('proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.displayName = 'proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.displayName = 'proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.repeatedFields_, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.displayName = 'proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.displayName = 'proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.repeatedFields_, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.displayName = 'proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.displayName = 'proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.displayName = 'proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.displayName = 'proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.displayName = 'proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    owner: (f = msg.getOwner()) && cs3_identity_user_v1beta1_resources_pb.User.toObject(includeInstance, f),
    type: jspb.Message.getFieldWithDefault(msg, 3, ""),
    name: jspb.Message.getFieldWithDefault(msg, 4, ""),
    quota: (f = msg.getQuota()) && cs3_storage_provider_v1beta1_resources_pb.Quota.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest;
  return proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new cs3_identity_user_v1beta1_resources_pb.User;
      reader.readMessage(value,cs3_identity_user_v1beta1_resources_pb.User.deserializeBinaryFromReader);
      msg.setOwner(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = new cs3_storage_provider_v1beta1_resources_pb.Quota;
      reader.readMessage(value,cs3_storage_provider_v1beta1_resources_pb.Quota.deserializeBinaryFromReader);
      msg.setQuota(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getOwner();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_identity_user_v1beta1_resources_pb.User.serializeBinaryToWriter
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getQuota();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      cs3_storage_provider_v1beta1_resources_pb.Quota.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.identity.user.v1beta1.User owner = 2;
 * @return {?proto.cs3.identity.user.v1beta1.User}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.getOwner = function() {
  return /** @type{?proto.cs3.identity.user.v1beta1.User} */ (
    jspb.Message.getWrapperField(this, cs3_identity_user_v1beta1_resources_pb.User, 2));
};


/**
 * @param {?proto.cs3.identity.user.v1beta1.User|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.setOwner = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.clearOwner = function() {
  return this.setOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.hasOwner = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string type = 3;
 * @return {string}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional Quota quota = 5;
 * @return {?proto.cs3.storage.provider.v1beta1.Quota}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.getQuota = function() {
  return /** @type{?proto.cs3.storage.provider.v1beta1.Quota} */ (
    jspb.Message.getWrapperField(this, cs3_storage_provider_v1beta1_resources_pb.Quota, 5));
};


/**
 * @param {?proto.cs3.storage.provider.v1beta1.Quota|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.setQuota = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.clearQuota = function() {
  return this.setQuota(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceRequest.prototype.hasQuota = function() {
  return jspb.Message.getField(this, 5) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f),
    storageSpace: (f = msg.getStorageSpace()) && cs3_storage_provider_v1beta1_resources_pb.StorageSpace.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse;
  return proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 3:
      var value = new cs3_storage_provider_v1beta1_resources_pb.StorageSpace;
      reader.readMessage(value,cs3_storage_provider_v1beta1_resources_pb.StorageSpace.deserializeBinaryFromReader);
      msg.setStorageSpace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getStorageSpace();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_storage_provider_v1beta1_resources_pb.StorageSpace.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.rpc.v1beta1.Status status = 2;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 2));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional StorageSpace storage_space = 3;
 * @return {?proto.cs3.storage.provider.v1beta1.StorageSpace}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.getStorageSpace = function() {
  return /** @type{?proto.cs3.storage.provider.v1beta1.StorageSpace} */ (
    jspb.Message.getWrapperField(this, cs3_storage_provider_v1beta1_resources_pb.StorageSpace, 3));
};


/**
 * @param {?proto.cs3.storage.provider.v1beta1.StorageSpace|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.setStorageSpace = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.clearStorageSpace = function() {
  return this.setStorageSpace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.CreateStorageSpaceResponse.prototype.hasStorageSpace = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    filtersList: jspb.Message.toObjectList(msg.getFiltersList(),
    proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.toObject, includeInstance),
    fieldMask: (f = msg.getFieldMask()) && google_protobuf_field_mask_pb.FieldMask.toObject(includeInstance, f),
    pageSize: jspb.Message.getFieldWithDefault(msg, 4, 0),
    pageToken: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest;
  return proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter;
      reader.readMessage(value,proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.deserializeBinaryFromReader);
      msg.addFilters(value);
      break;
    case 3:
      var value = new google_protobuf_field_mask_pb.FieldMask;
      reader.readMessage(value,google_protobuf_field_mask_pb.FieldMask.deserializeBinaryFromReader);
      msg.setFieldMask(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPageSize(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getFiltersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.serializeBinaryToWriter
    );
  }
  f = message.getFieldMask();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_field_mask_pb.FieldMask.serializeBinaryToWriter
    );
  }
  f = message.getPageSize();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getPageToken();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_ = [[2,3,4,5,6]];

/**
 * @enum {number}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.TermCase = {
  TERM_NOT_SET: 0,
  ID: 2,
  OWNER: 3,
  SPACE_TYPE: 4,
  PATH: 5,
  USER: 6
};

/**
 * @return {proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.TermCase}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.getTermCase = function() {
  return /** @type {proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.TermCase} */(jspb.Message.computeOneofCase(this, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    id: (f = msg.getId()) && cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId.toObject(includeInstance, f),
    owner: (f = msg.getOwner()) && cs3_identity_user_v1beta1_resources_pb.UserId.toObject(includeInstance, f),
    spaceType: jspb.Message.getFieldWithDefault(msg, 4, ""),
    path: jspb.Message.getFieldWithDefault(msg, 5, ""),
    user: (f = msg.getUser()) && cs3_identity_user_v1beta1_resources_pb.UserId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter;
  return proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = new cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId;
      reader.readMessage(value,cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 3:
      var value = new cs3_identity_user_v1beta1_resources_pb.UserId;
      reader.readMessage(value,cs3_identity_user_v1beta1_resources_pb.UserId.deserializeBinaryFromReader);
      msg.setOwner(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpaceType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 6:
      var value = new cs3_identity_user_v1beta1_resources_pb.UserId;
      reader.readMessage(value,cs3_identity_user_v1beta1_resources_pb.UserId.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId.serializeBinaryToWriter
    );
  }
  f = message.getOwner();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_identity_user_v1beta1_resources_pb.UserId.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      cs3_identity_user_v1beta1_resources_pb.UserId.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.Type = {
  TYPE_INVALID: 0,
  TYPE_NO: 1,
  TYPE_ID: 2,
  TYPE_OWNER: 3,
  TYPE_SPACE_TYPE: 4,
  TYPE_PATH: 5,
  TYPE_USER: 6
};

/**
 * optional Type type = 1;
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.Type}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.getType = function() {
  return /** @type {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.Type} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional StorageSpaceId id = 2;
 * @return {?proto.cs3.storage.provider.v1beta1.StorageSpaceId}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.getId = function() {
  return /** @type{?proto.cs3.storage.provider.v1beta1.StorageSpaceId} */ (
    jspb.Message.getWrapperField(this, cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId, 2));
};


/**
 * @param {?proto.cs3.storage.provider.v1beta1.StorageSpaceId|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.setId = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional cs3.identity.user.v1beta1.UserId owner = 3;
 * @return {?proto.cs3.identity.user.v1beta1.UserId}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.getOwner = function() {
  return /** @type{?proto.cs3.identity.user.v1beta1.UserId} */ (
    jspb.Message.getWrapperField(this, cs3_identity_user_v1beta1_resources_pb.UserId, 3));
};


/**
 * @param {?proto.cs3.identity.user.v1beta1.UserId|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.setOwner = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.clearOwner = function() {
  return this.setOwner(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.hasOwner = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string space_type = 4;
 * @return {string}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.getSpaceType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.setSpaceType = function(value) {
  return jspb.Message.setOneofField(this, 4, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.clearSpaceType = function() {
  return jspb.Message.setOneofField(this, 4, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.hasSpaceType = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string path = 5;
 * @return {string}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.setPath = function(value) {
  return jspb.Message.setOneofField(this, 5, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.clearPath = function() {
  return jspb.Message.setOneofField(this, 5, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.hasPath = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional cs3.identity.user.v1beta1.UserId user = 6;
 * @return {?proto.cs3.identity.user.v1beta1.UserId}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.getUser = function() {
  return /** @type{?proto.cs3.identity.user.v1beta1.UserId} */ (
    jspb.Message.getWrapperField(this, cs3_identity_user_v1beta1_resources_pb.UserId, 6));
};


/**
 * @param {?proto.cs3.identity.user.v1beta1.UserId|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.setUser = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter.prototype.hasUser = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Filter filters = 2;
 * @return {!Array<!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter>}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.getFiltersList = function() {
  return /** @type{!Array<!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter, 2));
};


/**
 * @param {!Array<!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter>} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.setFiltersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.addFilters = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.Filter, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.clearFiltersList = function() {
  return this.setFiltersList([]);
};


/**
 * optional google.protobuf.FieldMask field_mask = 3;
 * @return {?proto.google.protobuf.FieldMask}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.getFieldMask = function() {
  return /** @type{?proto.google.protobuf.FieldMask} */ (
    jspb.Message.getWrapperField(this, google_protobuf_field_mask_pb.FieldMask, 3));
};


/**
 * @param {?proto.google.protobuf.FieldMask|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.setFieldMask = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.clearFieldMask = function() {
  return this.setFieldMask(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.hasFieldMask = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 page_size = 4;
 * @return {number}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.getPageSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.setPageSize = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string page_token = 5;
 * @return {string}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.getPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesRequest.prototype.setPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f),
    storageSpacesList: jspb.Message.toObjectList(msg.getStorageSpacesList(),
    cs3_storage_provider_v1beta1_resources_pb.StorageSpace.toObject, includeInstance),
    nextPageToken: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse;
  return proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 3:
      var value = new cs3_storage_provider_v1beta1_resources_pb.StorageSpace;
      reader.readMessage(value,cs3_storage_provider_v1beta1_resources_pb.StorageSpace.deserializeBinaryFromReader);
      msg.addStorageSpaces(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNextPageToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getStorageSpacesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      cs3_storage_provider_v1beta1_resources_pb.StorageSpace.serializeBinaryToWriter
    );
  }
  f = message.getNextPageToken();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.rpc.v1beta1.Status status = 2;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 2));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated StorageSpace storage_spaces = 3;
 * @return {!Array<!proto.cs3.storage.provider.v1beta1.StorageSpace>}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.getStorageSpacesList = function() {
  return /** @type{!Array<!proto.cs3.storage.provider.v1beta1.StorageSpace>} */ (
    jspb.Message.getRepeatedWrapperField(this, cs3_storage_provider_v1beta1_resources_pb.StorageSpace, 3));
};


/**
 * @param {!Array<!proto.cs3.storage.provider.v1beta1.StorageSpace>} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.setStorageSpacesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.cs3.storage.provider.v1beta1.StorageSpace=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.storage.provider.v1beta1.StorageSpace}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.addStorageSpaces = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.cs3.storage.provider.v1beta1.StorageSpace, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.clearStorageSpacesList = function() {
  return this.setStorageSpacesList([]);
};


/**
 * optional string next_page_token = 4;
 * @return {string}
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.getNextPageToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.ListStorageSpacesResponse.prototype.setNextPageToken = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    storageSpace: (f = msg.getStorageSpace()) && cs3_storage_provider_v1beta1_resources_pb.StorageSpace.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest;
  return proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new cs3_storage_provider_v1beta1_resources_pb.StorageSpace;
      reader.readMessage(value,cs3_storage_provider_v1beta1_resources_pb.StorageSpace.deserializeBinaryFromReader);
      msg.setStorageSpace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getStorageSpace();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_storage_provider_v1beta1_resources_pb.StorageSpace.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional StorageSpace storage_space = 2;
 * @return {?proto.cs3.storage.provider.v1beta1.StorageSpace}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.getStorageSpace = function() {
  return /** @type{?proto.cs3.storage.provider.v1beta1.StorageSpace} */ (
    jspb.Message.getWrapperField(this, cs3_storage_provider_v1beta1_resources_pb.StorageSpace, 2));
};


/**
 * @param {?proto.cs3.storage.provider.v1beta1.StorageSpace|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.setStorageSpace = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.clearStorageSpace = function() {
  return this.setStorageSpace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceRequest.prototype.hasStorageSpace = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f),
    storageSpace: (f = msg.getStorageSpace()) && cs3_storage_provider_v1beta1_resources_pb.StorageSpace.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse;
  return proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 3:
      var value = new cs3_storage_provider_v1beta1_resources_pb.StorageSpace;
      reader.readMessage(value,cs3_storage_provider_v1beta1_resources_pb.StorageSpace.deserializeBinaryFromReader);
      msg.setStorageSpace(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getStorageSpace();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      cs3_storage_provider_v1beta1_resources_pb.StorageSpace.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.rpc.v1beta1.Status status = 2;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 2));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional StorageSpace storage_space = 3;
 * @return {?proto.cs3.storage.provider.v1beta1.StorageSpace}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.getStorageSpace = function() {
  return /** @type{?proto.cs3.storage.provider.v1beta1.StorageSpace} */ (
    jspb.Message.getWrapperField(this, cs3_storage_provider_v1beta1_resources_pb.StorageSpace, 3));
};


/**
 * @param {?proto.cs3.storage.provider.v1beta1.StorageSpace|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.setStorageSpace = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.clearStorageSpace = function() {
  return this.setStorageSpace(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.UpdateStorageSpaceResponse.prototype.hasStorageSpace = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    id: (f = msg.getId()) && cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest;
  return proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId;
      reader.readMessage(value,cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional StorageSpaceId id = 2;
 * @return {?proto.cs3.storage.provider.v1beta1.StorageSpaceId}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.getId = function() {
  return /** @type{?proto.cs3.storage.provider.v1beta1.StorageSpaceId} */ (
    jspb.Message.getWrapperField(this, cs3_storage_provider_v1beta1_resources_pb.StorageSpaceId, 2));
};


/**
 * @param {?proto.cs3.storage.provider.v1beta1.StorageSpaceId|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest} returns this
*/
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest} returns this
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceRequest.prototype.hasId = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    opaque: (f = msg.getOpaque()) && cs3_types_v1beta1_types_pb.Opaque.toObject(includeInstance, f),
    status: (f = msg.getStatus()) && cs3_rpc_v1beta1_status_pb.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse;
  return proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cs3_types_v1beta1_types_pb.Opaque;
      reader.readMessage(value,cs3_types_v1beta1_types_pb.Opaque.deserializeBinaryFromReader);
      msg.setOpaque(value);
      break;
    case 2:
      var value = new cs3_rpc_v1beta1_status_pb.Status;
      reader.readMessage(value,cs3_rpc_v1beta1_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOpaque();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cs3_types_v1beta1_types_pb.Opaque.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cs3_rpc_v1beta1_status_pb.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional cs3.types.v1beta1.Opaque opaque = 1;
 * @return {?proto.cs3.types.v1beta1.Opaque}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.getOpaque = function() {
  return /** @type{?proto.cs3.types.v1beta1.Opaque} */ (
    jspb.Message.getWrapperField(this, cs3_types_v1beta1_types_pb.Opaque, 1));
};


/**
 * @param {?proto.cs3.types.v1beta1.Opaque|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.setOpaque = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.clearOpaque = function() {
  return this.setOpaque(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.hasOpaque = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional cs3.rpc.v1beta1.Status status = 2;
 * @return {?proto.cs3.rpc.v1beta1.Status}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.getStatus = function() {
  return /** @type{?proto.cs3.rpc.v1beta1.Status} */ (
    jspb.Message.getWrapperField(this, cs3_rpc_v1beta1_status_pb.Status, 2));
};


/**
 * @param {?proto.cs3.rpc.v1beta1.Status|undefined} value
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse} returns this
*/
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse} returns this
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.storage.provider.v1beta1.DeleteStorageSpaceResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.cs3.storage.provider.v1beta1);
